### ISSUE TITLE
you should open issue tracker in new tab

### ISSUE THREAD

**Issue by heftrj** [stkraine/portfolio#1]
so like im totally perusing your rad website bro and i was like "woahskis i wonder what this **issues** link does", so i clicked it and it brought me to github which is like crazy cool you know but when I tried to go back to the dopest website ever, it made like a banana and split from my google chrome window. so i think it would be sick to like open all the links to a new tab maybe?

**Comment by stkraine** [comment]
I'll take a look at this upgrade!

**Comment by stkraine** [comment]
This was actually a super easy to do fix in which the `target="_blank"` tag was added to the anchor tag.
