### ISSUE TITLE
[BUG] letter 2 editor

### ISSUE THREAD

**Issue by heftrj** [stkraine/portfolio#12]
ya grammar sux

**Comment by heftrj** [comment]
In **high [\s] school**, the robots that I was working became taller than me ~at times~ and ~were solving~ **solved** fun problems within the F.I.R.S.T. programs set of challenges.

**Comment by heftrj** [comment]
this is a formal dislike crime for not having the images uploaded :(

**Comment by stkraine** [comment]
@heftrj any other comments that I need to change?
